Mike McDonald wrote in message <200211050453.gA54r1J32523@saturn.mikemac.com>:     In ACL:
    ;;; Compiling file ./input.lisp
    5007120 bytes have been tenured, next gc will be global.
    See the documentation for variable EXCL:*GLOBAL-GC-BEHAVIOR* for more information.
    ;;; Writing fasl file /home/mikemac/src/Lisp/McCLIM/input.fasl
    ;;; Fasl write complete
    ;     Loading product for module: "input".
    ; Fast loading /home/mikemac/src/Lisp/McCLIM/input.fasl
    Error: Attempt to add the method
           #<STANDARD-METHOD EVENT-QUEUE-SCHEDULE
             (STANDARD-EVENT-QUEUE T T T) @ #x20931b5a>
           to the generic function
           #<STANDARD-GENERIC-FUNCTION EVENT-QUEUE-SCHEDULE> but the method
           has more required arguments than the generic function.
      [condition type: PROGRAM-ERROR]

STANDARD-EVENT-QUEUE had a slot accessor defined by the name
EVENT-QUEUE-SCHEDULE which is now removed and so this error should now
be fixed.